name: ✨ 機能要望
description: 新機能・改善提案はこちら
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: 背景 / 解決したい課題
      description: 何が困っていて、どうなれば嬉しいか
      placeholder: 例) Gemの実行結果をテンプレ化して再利用しやすくしたい
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: 提案（やりたいこと）
      placeholder: 例) /gem run の結果を保存して、/gem history で参照できるようにする
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: スコープ / 受け入れ条件（任意）
      placeholder: |
        - [ ] 〜ができる
        - [ ] 〜の表示が崩れない
        - [ ] 〜の権限/公開範囲が守られる
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: 代替案（任意）
      placeholder: 例) 既存機能の運用で回避できるならその案
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: 補足
      description: 参考リンク、スクリーンショット、関連Issueなど
    validations:
      required: false

